services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: criteriaDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 061201
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  product-criteria:
    build: .
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/criteriaDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 061201

volumes:
  postgres_data:
